services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    restart: unless-stopped 
    ports:
      - '80:80'
      - '81:81'
      - '443:443' 
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt 

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam 
    volumes:
      - ./nextcloud/appdata:/config 
      - ./nextcloud/data:/data
    restart: unless-stopped 

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam 
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/movies:/data/movies 
      - ./sonarr/downloads:/data/tvshows
    restart: unless-stopped

  bitwarden:
    depends_on:
      - db
    env_file:
      - ./settings.env
    image: ghcr.io/bitwarden/self-host:beta
    restart: always
    volumes:
      - ./bitwarden/bitwarden:/etc/bitwarden
      - ./bitwarden/logs:/var/log/bitwarden
  db:
    environment:
      MARIADB_USER: "bitwarden"
      MARIADB_PASSWORD: "super_strong_password"
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    restart: always
    volumes:
      - ./bitwarden/data:/var/lib/mysql

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   environment:
  #     TZ: 'Europe/Amsterdam'
  #     WEBPASSWORD: 'TestAutoGenerated19191' # Change this
  #     DNSMASQ_LISTENING: all
  #   volumes:
  #     - ./pihole/etc-pihole:/etc/pihole
  #     - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "8081:80" # Web interface (avoid conflict with NPM on 80)
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    # It can be opened in localhost as well
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./openwebui:/app/backend/data
    depends_on:
      - ollama

  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./smokeping/config:/config
      - ./smokeping/data:/data
    ports:
      - 8099:80
    mem_limit: 4096m
    restart: unless-stopped

  # prowlarr:
  #   image: linuxserver/prowlarr:latest
  #   container_name: prowlarr
  #   volumes:
  #     - ./prowlarr/config:/config
  #     - ./prowlarr/backup:/data/Backup
  #   ports:
  #     - 9696:9696
  #   restart: unless-stopped
  #
  # sonarr:
  #   image: ghcr.io/hotio/sonarr:release
  #   container_name: sonarr
  #   ports:
  #     - "8989:8989"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Amsterdam
  #   volumes:
  #     - ./sonarr/config:/config
  #     - ./sonarr/downloads:/data
  #   restart: unless-stopped
  #
  # qbittorrent:
  #   image: linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   restart: unless-stopped
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=false"
  #   volumes:
  #     - ./qbittorrent/config:/config
  #   ports:
  #     - 8123:8123
  #     - 6881:6881
  #     - 6881:6881/udp
  #   environment:
  #     - WEBUI_PORT=8123
  #     - TORRENTING_PORT=6881
  #   healthcheck:
  #     start_period: 15s
  #
  # flaresolverr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   restart: unless-stopped
  #   ports:
  #     - 8191:8191
  #
  # nzbget:
  #   image: lscr.io/linuxserver/nzbget:latest
  #   container_name: nzbget
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Amsterdam
  #     - NZBGET_USER=nzbget #optional
  #     - NZBGET_PASS=tegbzn6789 #optional
  #   volumes:
  #     - ./nzbget/data:/config
  #   ports:
  #     - 6789:6789
  #   restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.molg.duckdns.org 
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    volumes:
      - ./homepage/config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    restart: unless-stopped
