apiVersion: v1
kind: Pod
metadata:
  name: migrate-pod
spec:
  containers:
  - name: mover
    image: alpine:3.18
    command: ["/bin/sh","-c","sleep 1d"]
    volumeMounts:
    - name: old
      mountPath: /from
    - name: new
      mountPath: /to
  volumes:
  - name: old
    persistentVolumeClaim:
      claimName: bitwarden-db-data
  - name: new
    persistentVolumeClaim:
      claimName: bitwarden-db-data-new
  restartPolicy: Never
