apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-db-data-new
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-db
  resources:
    requests:
      storage: 10Gi
